[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", ".git", ".jj", ".venv/"]
language-servers = ["ruff", "basedpyright"]
auto-format = true
formatter = { command = "uvx", args = ["sh", "-c", "ruff check --fix - | ruff format -"] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

[language-server.basedpyright]
command = 'uvx'
args = ['--from', 'basedpyright', 'basedpyright-langserver', "--stdio"]

[language-server.basedpyright.config]
python.pythonPath = ".venv/bin/python"

[language-server.ruff]
command = "uvx"
args = ["ruff","server"]
environment = { "RUFF_TRACE" = "messages" }

[[language]]
name = "php"
language-servers = [ "intelephense","tailwindcss-ls","vscode-html-language-server" ]
auto-format = true
